version: "0.2"
language: en
useGitignore: true
ignorePaths:
  - .git
  - .pnpm-store
  - node_modules
  - pnpm-lock.yaml
  - "**/*.~*"
  - "**/*.docx"
  - "**/*.png"
  - "**/*.emf"
words:
  - ACA
  - Ajv
  - BHP
  - BSD
  - Bugcrowd
  - CCIIO
  - CHIP
  - CMS
  - CMSGov
  - CMA
  - DHDSS
  - Dockerized
  - DSACMS
  - FDSH
  - FERPA
  - FFE
  - GED
  - HHSM
  - IFC
  - JSON
  - Medicaid
  - MEDH
  - MESH
  - MITG
  - Milarky
  - Milarsky
  - mTLS
  - NSC
  - OAuth
  - OAS
  - OHTP
  - OpenAPI
  - PII
  - PPACA
  - Redocly
  - Requester
  - SBOM
  - SBE
  - SDK
  - SHA
  - SPPO
  - SSN
  - TDS
  - TLS
  - UUID
  - WSDL
  - XSD
  - YAML
  - asOfDate
  - browsable
  - codeowners
  - contentType
  - decause
  - dockerized
  - dsacms
  - fdsh
  - fisma
  - heinrichreimer
  - hotfixed
  - jschema
  - localisation
  - messageID
  - nscRequest
  - nscResponse
  - openapi
  - plainlanguage
  - pnpm
  - postsecondary
  - skillsets
  - sublicensable
