version: "0.2"
language: en
useGitignore: true
ignorePaths:
  - .git
  - .pnpm-store
  - node_modules
  - pnpm-lock.yaml
  - COMMUNITY.md
  - public/gh-pages/data.json
  - "**/*.~*"
  - "**/*.docx"
  - "**/*.png"
  - "**/*.emf"
  - "**/*.py"
words:
  - Dockerized
  - browsable
  - Bugcrowd
  - ALPN
  - Authent
  - Respone
  - Verif
  - Countryof
  - xsds
  - APTCV
  - PHIII
  - IBAT
  - deviceinsight
  - podspec
  - objc
  - ridpv
  - SSAC
  - vlpv
  - soapprojects
  - CMCS
  - crosscore
  - mecv
  - soapui
  - esimecv
  - VeriSign
  - mfausrmgtusrauthvipauth
  - APNG
  - KHTML
  - Referer
  - cutover
  - asOfDate
  - contentType
  - messageID
  - nscRequest
  - nscResponse
  - vadr
  - vadrResponse
  - niem
  - appinfo
  - nillable
  - niem-xsd
  - niem-core
  - hix-core
  - plainlanguage
  - repolinter
  - skillsets
  - sublicensable
  - tlsv
  - codeowners
  - hotfixed
  - jschema
  - nonprod
  - pchar
  - httpbis
  - jsonseq
  - eventstream
  - subschema
  - byteranges
  - linkset
  - xyzzy
  - subschemas
  - postamble
  - uritemplate
  - scaffolder
  - aptc
  - ifsvv
  - ridp
  - ssacompositev
  - webrick
  - DQUOTE
  - HEXDIG
  - FDCF
  - FFEF
  - FFFFD
  - AFFFD
  - BFFFD
  - CFFFD
  - DFFFD
  - EFFFD
  - FFFFD
  - Busername
  - Cblack
  - Cbrown
  - Cinfo
  - Eabc
  - Anull
  - Equifax
  - CMSzONE
  - Redline
  - DSH
  - RD
  - QHP
  - CSR
  - ESI
  - MEC
  - IFSV
  - PVC
  - RRV
  - VLP
  - SSA
  - RIDP
  - FARS
  - VIP
  - EIDM
  - HCQIS
  - HARP
  - SNAPSHOT
  - WSDL
  - XSD
  - XML
  - REST
  - JSON
  - BSD
  - docx
  - zip
  - xml
  - pdf
  - png
  - emf
  - py
  - pnpm
  - node
  - pnpm-store
  - node_modules
  - pnpm-lock.yaml
  - Ajv
  - ACA
  - BHP
  - CCIIO
  - CHIP
  - CMS
  - CMSGov
  - CMA
  - DHDSS
  - DSACMS
  - FDSH
  - FERPA
  - FFE
  - GED
  - HHSM
  - IFC
  - Medicaid
  - MEDH
  - MESH
  - MITG
  - Milarky
  - Milarsky
  - mTLS
  - NSC
  - OAuth
  - OAS
  - OHTP
  - OpenAPI
  - PII
  - PPACA
  - Redocly
  - SBOM
  - SBE
  - SDK
  - SHA
  - SPPO
  - SSN
  - TDS
  - TLS
  - UUID
  - dsacms
  - fdsh
  - fisma
  - heinrichreimer
  - localisation
  - postsecondary
  - Martinsen
  - Burrell
  - stefanzweifel
  - akhilmhdh
  - pipefail
  - gacts
  - codejson
  - openapis
  - ucschar
  - iprivate
  - petstore
  - Edsger
  - edijkstra
  - Diṅnāga
  - diṅnāga
  - الخوارزميّ
  - BQAAA
  - AAQAAAABAAAA
  - ACAAQAAAABAAAA
  - ADAAQAAAABAAAA
  - AAAADO
  - QAAAAE
  - EQVQIHWP
  - ACTGCSAQANHQE
  - QAAAABJRU
  - Jggg
  - CMYK
  - PKCE
  - Aptos
  - Serv
  - Sftwr
  - DHSID
  - Elig
  - Mgmt
  - RESTJSON
  - PTDR
  - slcsp
  - SLCSP
  - Hsld
  - Initi
  - Inito
  - fars
  - ESIMEC
  - TRICARE
  - chdir
