version: "0.2"
language: en
useGitignore: true
ignorePaths:
  - .git
  - .pnpm-store
  - node_modules
  - pnpm-lock.yaml
  - COMMUNITY.md
  - "**/*.~*"
  - "**/*.docx"
  - "**/*.png"
  - "**/*.emf"
  - "**/*.py"
  - "**/*.toml"
  - "**/*.sh"
  - "**/*.json"
  - "**/*.yml"
  - "**/*.conf"
  - Dockerfile
words:
  - ACA
  - ALPN
  - Ajv
  - BHP
  - BSD
  - Bugcrowd
  - CCIIO
  - CHIP
  - CMS
  - CMSGov
  - CMA
  - DHDSS
  - Dockerized
  - DSACMS
  - FDSH
  - FERPA
  - FFE
  - GED
  - HHSM
  - IFC
  - JSON
  - Medicaid
  - MEDH
  - MESH
  - MITG
  - Milarky
  - Milarsky
  - mTLS
  - NSC
  - OAuth
  - OAS
  - OHTP
  - OpenAPI
  - PII
  - PPACA
  - Redocly
  - Requester
  - SBOM
  - SBE
  - SDK
  - SHA
  - SPPO
  - SSN
  - TDS
  - TLS
  - UUID
  - WSDL
  - XSD
  - YAML
  - asOfDate
  - browsable
  - codeowners
  - contentType
  - decause
  - dockerized
  - dsacms
  - fdsh
  - fisma
  - heinrichreimer
  - hotfixed
  - jschema
  - localisation
  - messageID
  - nonprod
  - nscRequest
  - nscResponse
  - openapi
  - plainlanguage
  - pnpm
  - postsecondary
  - repolinter
  - skillsets
  - sublicensable
  - tlsv
  - Martinsen
  - Burrell
  - stefanzweifel
  - akhilmhdh
  - pipefail
  - gacts
  - codejson
  - openapis
  - ucschar
  - iprivate
  - DQUOTE
  - HEXDIG
  - FDCF
  - FFEF
  - FFFD
  - AFFFD
  - BFFFD
  - CFFFD
  - DFFFD
  - EFFFD
  - FFFFD
  - petstore
  - pchar
  - httpbis
  - Cblack
  - Cbrown
  - Edsger
  - edijkstra
  - Diṅnāga
  - diṅnāga
  - الخوارزميّ
  - jsonseq
  - eventstream
  - BQAAA
  - AAQAAAABAAAA
  - ACAAQAAAABAAAA
  - ADAAQAAAABAAAA
  - AAAADO
  - QAAAAE
  - EQVQIHWP
  - ACTGCSAQANHQE
  - QAAAABJRU
  - Jggg
  - subschema
  - byteranges
  - myevent
  - Busername
  - linkset
  - xyzzy
  - subschemas
  - Cinfo
  - Eabc
  - CMYK
  - postamble
  - PKCE
  - uritemplate
  - scaffolder
  - Anull
  - Pydantic
  - pyproject
  - supervisord
