[supervisord]
nodaemon=true
user=root
logfile=/dev/stdout
logfile_maxbytes=0

[program:auth]
directory=/opt/mock-service/auth
command=python -m uvicorn app.main:app --host 0.0.0.0 --port 9000
environment=PYTHONPATH="/opt/mock-service/auth"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:api]
directory=/opt/mock-service/api
command=python -m uvicorn app.main:app --host 127.0.0.1 --port 8000
environment=PYTHONPATH="/opt/mock-service/api"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
